### ISSUE TITLE
comparison table -- "planned" status?

### ISSUE THREAD

**Issue by benjaminselfridge** [rsnikhil/Temporary_TGISA#1]
I was thinking it might make sense to add, beyond a simple "yes"/"no" value for some of the features, perhaps a "planned" value to indicate that although a feature may not be available at the present time, it will be developed. There are several such things for GRIFT (i.e. booting Linux, test generation), as I'm sure there are for the other specs, and it would be nice to be able to indicate this somehow.

**Comment by PeterSewell** [comment]
On 27/02/2019, Ben Selfridge <notifications@github.com> wrote:
> I was thinking it might make sense to add, beyond a simple "yes"/"no" value
> for some of the features, perhaps a "planned" value to indicate that
> although a feature may not be available at the present time, it will be
> developed. There are several such things for GRIFT (i.e. booting Linux, test
> generation), as I'm sure there are for the other specs, and it would be nice
> to be able to indicate this somehow.

I thought about that, but it would just end up with a lot of "planned"
of unclear status, for many of the models.  I think best to keep the
table clearly factual, and discuss plans in the template document
where one can also explain (eg) when such plans might be executed.

best,
Peter

**Comment by benjaminselfridge** [comment]
Makes sense.
